# Generated by Django 6.0.1 on 2026-02-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_class_alter_subject_class_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
    ]
